name: 'Merge Container Meta'

inputs:
  registry-image:
    description: "Image name to build for"
    required: true
  tags:
    description: "Tag settings for docker/metadata-action"
  digest-prefix:
    description: "Custom Digest prefix for multi-image build. alphanumeric and dash only"
    default: "digests"

runs:
  using: composite
  steps:
    - name: Prepare Variables
      id: prep
      env:
        REGISTRY_IMAGE: ${{ inputs.registry-image }}
      shell: bash
      run: |
        echo "registry-image-lower=${REGISTRY_IMAGE@L}" >> $GITHUB_OUTPUT

    - name: Download digests
      uses: actions/download-artifact@v4
      with:
        path: ${{ runner.temp }}/digests
        pattern: ${{ inputs.digest-prefix }}-*
        merge-multiple: true

    - name: Login to Github Container Repo
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ inputs.registry-image }}
        tags: ${{ inputs.tags }}

    - name: Create manifest list and push
      working-directory: ${{ runner.temp }}/digests
      shell: bash
      run: |
        docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
          $(printf '${{ steps.prep.outputs.registry-image-lower }}@sha256:%s ' *)

    - name: Inspect image
      shell: bash
      run: |
        docker buildx imagetools inspect ${{ steps.prep.outputs.registry-image-lower }}:${{ steps.meta.outputs.version }}
