name: 'Build Container'

inputs:
  registry-image:
    description: "Image name to build for"
    required: true
  push:
    description: "Do Push Final Image (string of `true` or `false`)"
    default: "false"
  digest-prefix:
    description: "Custom Digest prefix for multi-image build. alphanumeric and dash only"
    default: "digests"

runs:
  using: composite
  steps:
    - name: Prepare Variables
      id: prep
      env:
        REGISTRY_IMAGE: ${{ inputs.registry-image }}
      shell: bash
      run: |
        echo "registry-image-lower=${REGISTRY_IMAGE@L}" >> $GITHUB_OUTPUT

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Login to Github Container Repo
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ inputs.registry-image }}
        tags: ${{ inputs.tags }}

    - name: Build and push by digest
      uses: docker/build-push-action@v6
      id: build
      with:
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        # explicitly no tag, interferes with push-by-digest output
        tags: ${{ steps.prep.outputs.registry-image-lower }}
        # disables extra unknown/unknown in ghcr.io - enable if attestations wanted
        provenance: false
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=image,push-by-digest=true,name-canonical=true,push=${{ inputs.push }}

    - name: Export digest
      if: inputs.push == 'true'
      shell: bash
      id: export
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"
        echo "digest=${digest#sha256:}" >> $GITHUB_OUTPUT

    - name: Upload digest
      if: inputs.push == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.digest-prefix }}-${{ steps.export.outputs.digest }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1
